"""
Security scan report generator.

Renders OWASP scan results as Markdown or a self-contained, print-friendly
HTML report. Deterministic string templating — no LLM calls.
"""
import html
from datetime import datetime, timezone
from typing import Any, Dict, List

_RISK_BANDS = [
    (76, "Critical Risk"),
    (51, "High Risk"),
    (26, "Medium Risk"),
    (0, "Low Risk"),
]


def _risk_label(score: int) -> str:
    for threshold, label in _RISK_BANDS:
        if score >= threshold:
            return label
    return "Low Risk"


def _vulnerable_findings(scan_results: Dict[str, Any]) -> List[Dict[str, Any]]:
    return [f for f in scan_results.get("findings", []) if f.get("vulnerable")]


def generate_markdown_report(scan_results: Dict[str, Any], endpoint: str) -> str:
    """Generate a Markdown security report from a /security/scan response."""
    findings = scan_results.get("findings", [])
    summary = scan_results.get("summary", {})
    score = scan_results.get("risk_score", 0)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# API Security Scan Report",
        "",
        f"- **Target:** `{endpoint}`",
        f"- **Date:** {timestamp}",
        f"- **Framework:** OWASP API Security Top 10 (2023)",
        "",
        "## Executive Summary",
        "",
        f"**Risk Score: {score}/100 — {_risk_label(score)}**",
        "",
        f"- Tests executed: {summary.get('total_tests', len(findings))}",
        f"- Vulnerable findings: {summary.get('vulnerable_count', len(_vulnerable_findings(scan_results)))}",
        f"- Critical: {summary.get('critical', 0)} | High: {summary.get('high', 0)} "
        f"| Medium: {summary.get('medium', 0)} | Low: {summary.get('low', 0)}",
        f"- Scan duration: {scan_results.get('scan_duration_ms', 0)} ms",
        "",
        "## Findings",
        "",
        "| Severity | OWASP Category | Finding | Status | HTTP |",
        "|---|---|---|---|---|",
    ]
    for f in findings:
        lines.append(
            f"| {f.get('severity', '')} "
            f"| {f.get('owasp_category', '')} "
            f"| {f.get('title', '').replace('|', '\\|')} "
            f"| {f.get('finding', '')} "
            f"| {f.get('actual_status', '')} |"
        )

    lines += ["", "## Remediation Checklist", ""]
    vulnerable = _vulnerable_findings(scan_results)
    if not vulnerable:
        lines.append("- [x] No vulnerable findings. Keep re-scanning on every release.")
    for f in vulnerable:
        lines.append(
            f"- [ ] **[{f.get('severity', '')}] {f.get('title', '')}** "
            f"({f.get('owasp_category', '')}) — {f.get('remediation', '')}"
        )

    lines += [
        "",
        "---",
        "_Generated by Smart API Testing Assistant. Authorized testing only — "
        "scan solely APIs you own or have written permission to test._",
        "",
    ]
    return "\n".join(lines)


_SEVERITY_COLORS = {
    "Critical": "#7f1d1d",
    "High": "#dc2626",
    "Medium": "#ea580c",
    "Low": "#ca8a04",
}


def generate_html_report(scan_results: Dict[str, Any], endpoint: str) -> str:
    """Generate a color-coded, print-friendly HTML security report."""
    findings = scan_results.get("findings", [])
    summary = scan_results.get("summary", {})
    score = scan_results.get("risk_score", 0)
    label = _risk_label(score)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rows = []
    for f in findings:
        sev = f.get("severity", "")
        color = _SEVERITY_COLORS.get(sev, "#6b7280")
        status_color = "#dc2626" if f.get("finding") == "Vulnerable" else (
            "#22c55e" if f.get("finding") == "Secure" else "#ca8a04"
        )
        rows.append(
            f"<tr>"
            f"<td><span class='badge' style='background:{color}'>{html.escape(sev)}</span></td>"
            f"<td>{html.escape(str(f.get('owasp_category', '')))}</td>"
            f"<td>{html.escape(str(f.get('title', '')))}</td>"
            f"<td style='color:{status_color};font-weight:600'>{html.escape(str(f.get('finding', '')))}</td>"
            f"<td>{html.escape(str(f.get('actual_status', '')))}</td>"
            f"</tr>"
            f"<tr class='detail'><td colspan='5'>"
            f"<strong>Remediation:</strong> {html.escape(str(f.get('remediation', '')))}<br>"
            f"<strong>Payload:</strong> <code>{html.escape(str(f.get('payload_used', {})))}</code>"
            f"</td></tr>"
        )

    gauge_color = (
        "#dc2626" if score >= 76 else
        "#ea580c" if score >= 51 else
        "#ca8a04" if score >= 26 else
        "#22c55e"
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>API Security Scan Report</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; color: #1a1a2e; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }}
  h1 {{ font-size: 1.5rem; }}
  .meta {{ color: #6b7280; font-size: 0.9rem; margin-bottom: 1.5rem; }}
  .gauge {{ background: #e2e8f0; border-radius: 8px; height: 24px; overflow: hidden; margin: 0.5rem 0; }}
  .gauge-fill {{ height: 100%; background: {gauge_color}; width: {score}%; }}
  .score {{ font-size: 1.25rem; font-weight: 700; color: {gauge_color}; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; font-size: 0.875rem; }}
  th, td {{ border: 1px solid #e5e7eb; padding: 8px 10px; text-align: left; vertical-align: top; }}
  th {{ background: #f4f6f8; }}
  .badge {{ color: #fff; padding: 2px 8px; border-radius: 10px; font-size: 0.75rem; }}
  .detail td {{ background: #f8fafc; font-size: 0.8125rem; color: #374151; }}
  .warn {{ background: #fef3c7; border: 1px solid #f59e0b; border-radius: 6px; padding: 10px 14px; font-size: 0.875rem; margin-bottom: 1rem; }}
  code {{ background: #1e293b; color: #e2e8f0; padding: 2px 6px; border-radius: 4px; font-size: 0.78rem; word-break: break-all; }}
  @media print {{ body {{ margin: 0; }} }}
</style>
</head>
<body>
  <h1>API Security Scan Report</h1>
  <p class="meta">Target: <code>{html.escape(endpoint)}</code> &middot; {timestamp} &middot; OWASP API Security Top 10 (2023)</p>
  <div class="warn">&#9888; Authorized testing only. This report is for APIs you own or have written permission to test.</div>

  <h2>Executive Summary</h2>
  <p class="score">Risk Score: {score}/100 &mdash; {label}</p>
  <div class="gauge"><div class="gauge-fill"></div></div>
  <p>Tests executed: {summary.get('total_tests', len(findings))} &middot;
     Vulnerable: {summary.get('vulnerable_count', len(_vulnerable_findings(scan_results)))} &middot;
     Critical: {summary.get('critical', 0)} &middot; High: {summary.get('high', 0)} &middot;
     Medium: {summary.get('medium', 0)} &middot; Low: {summary.get('low', 0)} &middot;
     Duration: {scan_results.get('scan_duration_ms', 0)} ms</p>

  <h2>Findings</h2>
  <table>
    <thead><tr><th>Severity</th><th>OWASP Category</th><th>Finding</th><th>Status</th><th>HTTP</th></tr></thead>
    <tbody>{''.join(rows)}</tbody>
  </table>

  <p class="meta">Generated by Smart API Testing Assistant.</p>
</body>
</html>
"""
